In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

# Series and Dataframe
- Series  (rows or Columns)
- Dataframe (Rows and Columns)

In [4]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
pd.Series(['apple','orange','Banana'])

0     apple
1    orange
2    Banana
dtype: str

In [9]:
vegetables=pd.Series(('Brinjal','Potato','Tomato'))
vegetables.name="Vegetable"
vegetables

0    Brinjal
1     Potato
2     Tomato
Name: Vegetable, dtype: str

# Dataframe

## Dataframe using List

In [17]:
fruit1=['apple','red',150]
fruit2=['Grapes','purple',50]
fruit3=['cherry','red',120]
fruits=[fruit1,fruit2,fruit3]
df=pd.DataFrame(fruits)
df.columns=["Name","Color","Price"]
df

     Name   Color  Price
0   apple     red    150
1  Grapes  purple     50
2  cherry     red    120

## Dataframe using Tuple

In [20]:
fruit1=('apple','red',150)
fruit2=('Grapes','purple',50)
fruit3=('cherry','red',120)
fruits=[fruit1,fruit2,fruit3]
df=pd.DataFrame(fruits)
df.columns=["Name","Color","Price"]
df

     Name   Color  Price
0   apple     red    150
1  Grapes  purple     50
2  cherry     red    120

## Dataframe using Dictionary

In [22]:
item={
    'fruits':['apple','orange','Banana'],
    "colors":['red','orange','yellow']
}
pd.DataFrame(item)

   fruits  colors
0   apple     red
1  orange  orange
2  Banana  yellow

# Path
- 2 types 
- 1. Absolute path
- 2. Relative

In [4]:
df=pd.read_csv(r'D:\Skillfort\SkillFortClass\data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]