In [1]:
import pandas as pd

# Function
- Custom Function (series,Dataframe) => .apply() eg: df.apply(custom_func)
  - NOTE: for dataframe need to mention pd.Series in function eg(def convert_function(column:pd.Series):)
  - column.str.lower().str.replace(' ','') for Chaining
    - assign() is used to create or update columns,
    - while apply() is used to modify values using a function
- Aggregate Function
    - sum,product,prod,mean,median,min,max,count,size,std,var
      - eg: for Dataframe: df.sum(numeric_only=True)
    - groupby eg: df['weight'].groupby(df['origin']).max()
        - df.groupby('origin').max(numeric_only=True)
        - df.groupby('origin')['weight'].max(numeric_only=True)
- unique()
- Map
  - interate with Every integer Element
  - apply
- Lambda
- Pipe (series / continous operation) .pipe().pipe()

In [2]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [4]:
def convert_word(a):
    print( a.lower())
convert_word("WElocme")

welocme

In [18]:
def convert_word(a:str):
    if not isinstance(a,str):
        raise TypeError("Erorrrrrrrrr")
    print(a)
convert_word("WElocme")
convert_word(12)

WElocme

TypeError: Erorrrrrrrrr

In [6]:
def convert_word(a):
    return( a.lower())
df['origin'].apply(convert_word)

0      japan
1         us
2      india
3    germany
4         us
Name: origin, dtype: str

In [22]:
df_str=df[['car','origin']]
df_str

       car   origin
0     Ford    Japan
1   Jaguar       US
2     Audi    India
3  Hyundai  Germany
4     Tata       US

In [27]:
def convert_word(a):
    return( a.str.lower().str.upper())
df_str.apply(convert_word)

       car   origin
0     FORD    JAPAN
1   JAGUAR       US
2     AUDI    INDIA
3  HYUNDAI  GERMANY
4     TATA       US

In [32]:
def convert_word(a):
    return( a.lower())
df.assign(
    "Modified"=df['origin'].apply(convert_word)
    )

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (961119150.py, line 4)