In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../../../car_data_500.csv')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
...,...,...,...,...,...,...,...,...,...
495,Toyota,18.9,6.0,1583,120,1918,11.3,79,India
496,Hyundai,16.5,4.0,3131,128,4312,13.1,77,US
497,Maruthi,24.8,4.0,3692,236,3951,12.5,79,US
498,Tata,12.2,4.0,1624,252,3795,9.1,79,South Korea
499,Honda,17.0,8.0,3408,110,3505,16.4,79,US

## under sampling 
- max record lenthu min records edukrathu

In [4]:
df.shape

(500, 9)

In [3]:
df.sample(n=250) # take random values

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
160,Jaguar,17.7,6.0,1979,82,4485,11.8,78,South Korea
349,BMW,23.4,4.0,2170,147,3387,10.2,71,Germany
472,Hyundai,18.1,4.0,4926,205,3896,14.3,70,Germany
38,Honda,11.0,4.0,4203,194,2131,9.2,72,US
315,Ford,13.9,4.0,4459,88,3351,15.6,70,India
...,...,...,...,...,...,...,...,...,...
314,BMW,22.0,6.0,3406,239,2157,7.8,74,US
494,Maruthi,14.9,6.0,2052,90,4077,8.1,70,US
311,Honda,15.9,4.0,4941,179,3892,10.7,80,US
60,Toyota,23.8,6.0,4288,179,4143,8.5,73,South Korea
432,Hyundai,16.7,4.0,3661,160,3319,15.2,76,South Korea

In [6]:
# 30percertage data
df.sample(frac=.3) # Fraction

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
64,Kia,18.8,4.0,1431,189,4266,12.5,79,Japan
387,Honda,24.0,4.0,4004,206,3442,17.5,75,US
363,Audi,10.1,4.0,2782,196,3750,17.6,79,India
264,Ford,19.7,6.0,3834,90,2742,17.4,72,Germany
419,Hyundai,21.8,6.0,4635,124,3536,12.0,76,South Korea
...,...,...,...,...,...,...,...,...,...
217,Kia,15.2,6.0,4500,110,4242,14.8,75,South Korea
126,Jaguar,22.1,4.0,2511,72,3700,12.3,76,Germany
88,Tata,15.2,4.0,2191,236,3623,13.3,70,India
89,Maruthi,17.0,6.0,3615,249,3274,9.9,77,Germany
327,Audi,22.5,8.0,2197,88,4355,11.6,74,India

## over Sampling
- total record 500 need 1000 records
- **Sampling without replacement** Dont replace the item from the population wheever you pick it up. So the same item cannot be picked more than once in the sample
- **Sampling with Replacement** Replace the item from the population wheever you pick it up. so htere is a change of picking the same item again in the sample

df.sample(n=1000,replace=True)

df.sample(n=1000,replace=True).sort_values(['car','MPO']) .head(60)