In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../../../car_data_500.csv')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
...,...,...,...,...,...,...,...,...,...
495,Toyota,18.9,6.0,1583,120,1918,11.3,79,India
496,Hyundai,16.5,4.0,3131,128,4312,13.1,77,US
497,Maruthi,24.8,4.0,3692,236,3951,12.5,79,US
498,Tata,12.2,4.0,1624,252,3795,9.1,79,South Korea
499,Honda,17.0,8.0,3408,110,3505,16.4,79,US

## under sampling 
- max record lenthu min records edukrathu

In [4]:
df.shape

(500, 9)

In [5]:
df.sample(n=100) # take random values

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
360,BMW,21.0,6.0,3210,155,3294,14.1,76,US
307,Maruthi,14.2,8.0,4147,284,2709,10.2,75,South Korea
36,Tata,21.6,6.0,4192,181,2907,11.0,72,US
129,Ford,12.1,6.0,2449,176,2242,10.2,79,Germany
317,BMW,24.7,4.0,4162,97,3480,11.8,74,India
...,...,...,...,...,...,...,...,...,...
445,Honda,11.5,4.0,2841,81,2448,12.0,74,US
269,Honda,23.3,8.0,2324,115,1821,15.1,70,Germany
178,Toyota,20.8,4.0,1455,195,2182,9.3,73,South Korea
460,BMW,24.5,6.0,3443,104,2851,7.6,73,Germany
98,Kia,17.2,8.0,3710,80,3435,17.4,80,Germany

In [6]:
# 30percertage data
df.sample(frac=.3) # Fraction

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
16,Audi,20.7,4.0,4391,236,3950,16.9,72,Japan
116,Honda,17.6,4.0,4947,111,2616,17.2,80,India
8,BMW,17.5,6.0,3801,221,1818,10.8,76,South Korea
228,Hyundai,11.5,6.0,1648,86,3994,7.9,72,Japan
46,Tata,12.8,6.0,3334,128,3666,11.3,71,Japan
...,...,...,...,...,...,...,...,...,...
82,Toyota,12.8,6.0,4623,269,4458,17.6,78,US
215,Hyundai,19.3,4.0,2504,249,3508,10.3,73,India
127,Tata,24.4,4.0,4559,96,3257,14.3,80,India
197,Hyundai,11.0,4.0,2267,177,3951,15.4,74,South Korea
165,Audi,19.7,4.0,4668,292,1867,10.9,75,Japan

## over Sampling
- total record 500 need 1000 records
- **Sampling without replacement** Dont replace the item from the population wheever you pick it up. So the same item cannot be picked more than once in the sample
- **Sampling with Replacement** Replace the item from the population wheever you pick it up. so htere is a change of picking the same item again in the sample

In [9]:
df.sample(n=1000,replace=True)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
141,Honda,19.4,6.0,3371,170,2710,10.9,76,US
149,Kia,15.4,4.0,4559,81,1923,17.1,75,India
122,Toyota,20.8,4.0,1980,76,3263,15.0,70,Germany
109,Maruthi,24.7,4.0,1577,124,2713,8.8,76,US
96,Honda,17.9,4.0,3576,266,3841,15.7,72,South Korea
...,...,...,...,...,...,...,...,...,...
227,Maruthi,10.1,4.0,1714,219,2682,14.3,73,South Korea
271,Tata,16.6,4.0,3379,297,2482,7.3,73,India
447,Audi,17.9,4.0,1404,287,3282,9.7,79,South Korea
217,Kia,15.2,6.0,4500,110,4242,14.8,75,South Korea
148,BMW,21.6,4.0,4443,206,4017,9.1,74,Japan

In [11]:
df.sample(n=1000,replace=True).sort_values(['car','MPO']) .head(60)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
363,Audi,10.1,4.0,2782,196,3750,17.6,79,India
427,Audi,10.9,8.0,3972,136,3127,16.1,75,US
427,Audi,10.9,8.0,3972,136,3127,16.1,75,US
427,Audi,10.9,8.0,3972,136,3127,16.1,75,US
427,Audi,10.9,8.0,3972,136,3127,16.1,75,US
206,Audi,12.0,4.0,1902,99,4460,9.5,73,Japan
180,Audi,12.1,4.0,1861,296,3356,7.8,70,Japan
180,Audi,12.1,4.0,1861,296,3356,7.8,70,Japan
69,Audi,12.5,6.0,1635,161,3036,12.1,71,US
69,Audi,12.5,6.0,1635,161,3036,12.1,71,US
44,Audi,13.5,6.0,4187,107,4297,15.9,73,South Korea
340,Audi,13.9,8.0,3728,230,2876,15.1,79,Germany
340,Audi,13.9,8.0,3728,230,2876,15.1,79,Germany
298,Audi,15.0,6.0,3763,147,2056,9.8,72,Germany
298,Audi,15.0,6.0,3763,147,2056,9.8,72,Germany
266,Audi,15.5,6.0,2214,126,4134,11.2,77,South Korea
266,Audi,15.5,6.0,2214,126,4134,11.2,77,South Korea
266,Audi,15.5,6.0,2214,126,4134,11.2,77,South Korea
266,Audi,15.5,6.0,2214,126,4134,11.2,77,South Korea
37,Audi,15.6,6.0,1278,248,2936,9.5,74,US
37,Audi,15.6,6.0,1278,248,2936,9.5,74,US
91,Audi,15.7,6.0,4608,158,2979,13.5,80,South Korea
52,Audi,15.7,4.0,1286,261,3363,12.2,73,South Korea
52,Audi,15.7,4.0,1286,261,3363,12.2,73,South Korea
91,Audi,15.7,6.0,4608,158,2979,13.5,80,South Korea
91,Audi,15.7,6.0,4608,158,2979,13.5,80,South Korea
52,Audi,15.7,4.0,1286,261,3363,12.2,73,South Korea
296,Audi,16.0,4.0,4390,216,4035,14.4,77,India
296,Audi,16.0,4.0,4390,216,4035,14.4,77,India
130,Audi,16.1,4.0,1722,109,3922,11.4,79,Japan
130,Audi,16.1,4.0,1722,109,3922,11.4,79,Japan
354,Audi,17.2,4.0,3648,289,1852,7.8,70,US
10,Audi,17.3,4.0,3801,130,2255,7.0,80,South Korea
10,Audi,17.3,4.0,3801,130,2255,7.0,80,South Korea
10,Audi,17.3,4.0,3801,130,2255,7.0,80,South Korea
10,Audi,17.3,4.0,3801,130,2255,7.0,80,South Korea
299,Audi,17.8,8.0,4492,153,2346,13.9,70,Germany
337,Audi,17.8,4.0,1382,99,3493,17.7,72,Japan
447,Audi,17.9,4.0,1404,287,3282,9.7,79,South Korea
447,Audi,17.9,4.0,1404,287,3282,9.7,79,South Korea
107,Audi,17.9,4.0,3416,154,4406,14.0,71,India
275,Audi,18.1,4.0,2243,206,2076,17.7,73,Germany
275,Audi,18.1,4.0,2243,206,2076,17.7,73,Germany
185,Audi,19.5,4.0,4737,185,3322,16.2,72,US
138,Audi,19.6,4.0,1687,193,4109,17.1,76,India
138,Audi,19.6,4.0,1687,193,4109,17.1,76,India
165,Audi,19.7,4.0,4668,292,1867,10.9,75,Japan
493,Audi,19.8,4.0,3080,157,3201,16.6,76,South Korea
493,Audi,19.8,4.0,3080,157,3201,16.6,76,South Korea
469,Audi,20.7,6.0,4474,115,2034,8.8,77,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
12,Audi,21.6,6.0,3872,97,2932,14.1,74,South Korea
12,Audi,21.6,6.0,3872,97,2932,14.1,74,South Korea
33,Audi,21.9,4.0,1975,143,3574,13.0,76,India
33,Audi,21.9,4.0,1975,143,3574,13.0,76,India
33,Audi,21.9,4.0,1975,143,3574,13.0,76,India
439,Audi,22.3,4.0,1469,75,3278,12.9,74,India
327,Audi,22.5,8.0,2197,88,4355,11.6,74,India